name: Build and publish a Docker image to ghcr.io
on:

  # publish on releases, e.g. v2.1.13 (image tagged as "2.1.13" - "v" prefix is removed)
  release:
    types: [ published ]

  # publish on pushes to the main branch (image tagged as "latest")
  push:
    branches:
      - master

jobs:
          
  docker_publish_java17:
    runs-on: "ubuntu-20.04"

    steps:
      - uses: actions/checkout@v2
      - name: Set lower case owner name
        run: |
          echo "REPO_LC=${REPO,,}" >>${GITHUB_ENV}
        env:
          REPO: '${{ github.repository }}'

      - name: Build and publish an image for ${{ env.REPO_LC }}-java17
        uses: macbre/push-to-ghcr@master
        with:
          dockerfile: Dockerfile
          image_name: ${{ env.REPO_LC }}-java17
          github_token: ${{ secrets.GITHUB_TOKEN }}
